### ISSUE TITLE
Option to speed up gifs?

### ISSUE THREAD

**Issue by Chaphasilor** [tpkn/web-videos#1]
Hey, 

I really love the simplicity of your module and I was wondering if you could maybe add an option to speed up the gifs?  
I'm trying to generate video previews/summaries and want the gifs to briefly show a few frames of the video.

For example, setting a 'duration' to 10 seconds and 'frames' to 100 would mean the gif that is created from the video is exactly 10 seconds long and has 100 frames, each frame being taken from a matching spot of the video. The first frame would be after 1%, second after 2% and so on.

Is this possible or do I need to look somewhere else?

Best, Chap

**Comment by tpkn** [comment]
I will see what I can do)

**Comment by tpkn** [comment]
I got a little carried away... And the result is a separate module - https://github.com/tpkn/video-preview

**Comment by Chaphasilor** [comment]
Great to see! I'm trying it out right now!
